Repository AlesInfiny/maia, pull requests merged in 2025-07, with the labels that each got.

#2706 [DOC] CSS の設定と CSS フレームワークの適用 を最新化する
  documents/contents/guidebooks/how-to-develop/vue-js/css.md
Labels: target: ガイド/AP開発手順

#2709 [AzureADB2C] 型情報を利用したルール vueTsConfigs.recommendedTypeChecked を使用するように変更
  samples/azure-ad-b2c-sample/auth-frontend/app/src/api-client/index.ts
  samples/azure-ad-b2c-sample/auth-frontend/app/src/services/authentication/authentication-service.ts
  samples/azure-ad-b2c-sample/auth-frontend/app/src/services/user/user-service.ts
  samples/azure-ad-b2c-sample/auth-frontend/app/src/stores/server-time/server-time.ts
  samples/azure-ad-b2c-sample/auth-frontend/eslint.config.ts
Labels: target: Azure AD B2C Auth

#2724 [Dressca]マルチルートワークスペースを用いてフロントエンドで VS CODE の各拡張機能が動作するようにする
  samples/web-csr/dressca-frontend/.markdownlint-cli2.yaml
  samples/web-csr/dressca-frontend/.markdownlint.yaml
  samples/web-csr/dressca-frontend/.textlintignore
  samples/web-csr/dressca-frontend/.textlintrc
  samples/web-csr/dressca-frontend/.vscode/extensions.json
  samples/web-csr/dressca-frontend/.vscode/settings.json
  samples/web-csr/dressca-frontend/admin/.gitignore
  samples/web-csr/dressca-frontend/admin/.markdownlint-cli2.yaml
  samples/web-csr/dressca-frontend/admin/.textlintignore
  samples/web-csr/dressca-frontend/admin/.textlintrc
  samples/web-csr/dressca-frontend/admin/.vscode/extensions.json
  samples/web-csr/dressca-frontend/admin/.vscode/settings.json
  samples/web-csr/dressca-frontend/consumer/.markdownlint-cli2.yaml
  samples/web-csr/dressca-frontend/consumer/.textlintignore
  samples/web-csr/dressca-frontend/consumer/.textlintrc
  samples/web-csr/dressca-frontend/consumer/.vscode/extensions.json
  samples/web-csr/dressca-frontend/consumer/.vscode/settings.json
  samples/web-csr/dressca-frontend/dressca-frontend.code-workspace
Labels: target: Dressca

#2736 (AzureADB2C)code-workspaceの導入に合わせてドキュメントを最新化
  samples/azure-ad-b2c-sample/README.md
Labels: target: サンプル解説

#2749 StylelintとPrettierを分離する
  samples/azure-ad-b2c-sample/auth-frontend/app/package.json
  samples/web-csr/dressca-frontend/.stylelintrc.js
  samples/web-csr/dressca-frontend/admin/package.json
  samples/web-csr/dressca-frontend/consumer/package.json
  samples/web-csr/dressca-frontend/package-lock.json
Labels: target: Dressca, target: Azure AD B2C Auth

#2755 [DOC]ワークスペースの設定 > VS Code 上のワークスペースの設定 を追加
  documents/contents/guidebooks/how-to-develop/vue-js/setting-workspaces.md
  documents/hooks/github_markdown_fetcher.py
Labels: target: ガイド/AP開発手順

#2732 [Dressca/AzureADB2C]型情報を使用したLintルールを適用する
  samples/azure-ad-b2c-sample/auth-frontend/eslint.config.ts
  samples/azure-ad-b2c-sample/auth-frontend/tsconfig.json
  samples/web-csr/dressca-frontend/admin/mock/handlers/assets-handler.ts
  samples/web-csr/dressca-frontend/admin/mock/handlers/catalog-items-handler.ts
  samples/web-csr/dressca-frontend/admin/src/App.vue
  samples/web-csr/dressca-frontend/admin/src/api-client/index.ts
  samples/web-csr/dressca-frontend/admin/src/services/authentication/authentication-service.ts
  samples/web-csr/dressca-frontend/admin/src/shared/error-handler/global-error-handler.ts
  samples/web-csr/dressca-frontend/admin/src/stores/authentication/authentication.ts
  samples/web-csr/dressca-frontend/admin/src/views/__tests__/ItemsAddView.spec.ts
  samples/web-csr/dressca-frontend/admin/src/views/__tests__/ItemsEditView.spec.ts
  samples/web-csr/dressca-frontend/admin/src/views/__tests__/ItemsView.spec.ts
  samples/web-csr/dressca-frontend/admin/src/views/authentication/LoginView.vue
  samples/web-csr/dressca-frontend/admin/src/views/catalog/ItemsAddView.vue
  samples/web-csr/dressca-frontend/admin/src/views/catalog/ItemsEditView.vue
  samples/web-csr/dressca-frontend/admin/src/views/catalog/ItemsView.vue
  samples/web-csr/dressca-frontend/admin/src/views/error/ErrorView.vue
  samples/web-csr/dressca-frontend/admin/src/views/error/NotFoundView.vue
  samples/web-csr/dressca-frontend/admin/tsconfig.app.json
  samples/web-csr/dressca-frontend/consumer/mock/handlers/assets-handler.ts
  samples/web-csr/dressca-frontend/consumer/mock/handlers/baskets-handler.ts
  samples/web-csr/dressca-frontend/consumer/mock/handlers/ordering-handler.ts
  samples/web-csr/dressca-frontend/consumer/src/App.vue
  samples/web-csr/dressca-frontend/consumer/src/api-client/index.ts
  samples/web-csr/dressca-frontend/consumer/src/components/__tests__/common/CarouselSlider.spec.ts
  samples/web-csr/dressca-frontend/consumer/src/components/common/NotificationToast.vue
  samples/web-csr/dressca-frontend/consumer/src/components/icons/IconCommunity.vue
  samples/web-csr/dressca-frontend/consumer/src/components/icons/IconDocumentation.vue
  samples/web-csr/dressca-frontend/consumer/src/components/icons/IconEcosystem.vue
  samples/web-csr/dressca-frontend/consumer/src/components/icons/IconSupport.vue
  samples/web-csr/dressca-frontend/consumer/src/components/icons/IconTooling.vue
  samples/web-csr/dressca-frontend/consumer/src/services/authentication/authentication-service.ts
  samples/web-csr/dressca-frontend/consumer/src/services/catalog/catalog-service.ts
  samples/web-csr/dressca-frontend/consumer/src/shared/error-handler/global-error-handler.ts
  samples/web-csr/dressca-frontend/consumer/src/stores/authentication/authentication.ts
  samples/web-csr/dressca-frontend/consumer/src/views/__tests__/basket/BasketView.spec.ts
  samples/web-csr/dressca-frontend/consumer/src/views/authentication/LoginView.vue
  samples/web-csr/dressca-frontend/consumer/src/views/basket/BasketView.vue
  samples/web-csr/dressca-frontend/consumer/src/views/catalog/CatalogView.vue
  samples/web-csr/dressca-frontend/consumer/src/views/ordering/CheckoutView.vue
  samples/web-csr/dressca-frontend/consumer/src/views/ordering/DoneView.vue
  samples/web-csr/dressca-frontend/consumer/tsconfig.app.json
  samples/web-csr/dressca-frontend/consumer/tsconfig.vitest.json
  samples/web-csr/dressca-frontend/eslint.config.ts
  samples/web-csr/dressca-frontend/tsconfig.json
Labels: target: Dressca

#2753 バッチの起動手順を追記
  .textlintrc
  documents/contents/samples/index.md
  documents/contents/samples/spring-batch/index.md
  documents/mkdocs.yml
Labels: target: サンプル解説

#2799 openapi-generator v7.14.0にアップデートする
  samples/azure-ad-b2c-sample/auth-frontend/app/openapitools.json
  samples/azure-ad-b2c-sample/auth-frontend/app/src/generated/api-client/.openapi-generator/VERSION
  samples/azure-ad-b2c-sample/auth-frontend/app/src/generated/api-client/common.ts
  samples/web-csr/dressca-frontend/admin/openapitools.json
  samples/web-csr/dressca-frontend/admin/src/generated/api-client/.openapi-generator/VERSION
  samples/web-csr/dressca-frontend/admin/src/generated/api-client/common.ts
  samples/web-csr/dressca-frontend/consumer/openapitools.json
  samples/web-csr/dressca-frontend/consumer/src/generated/api-client/.openapi-generator/VERSION
  samples/web-csr/dressca-frontend/consumer/src/generated/api-client/common.ts
Labels: target: Dressca, target: Azure AD B2C Auth

#2826 VitestとCypressのテストスイートの検索がうまくできていない不具合を修正
  samples/azure-ad-b2c-sample/auth-frontend/eslint.config.ts
  samples/web-csr/dressca-frontend/eslint.config.ts
Labels: 不具合, target: Dressca, target: Azure AD B2C Auth

#2838 dependencies.gradleのガイドにlog4j2の依存関係を追加
  documents/contents/guidebooks/how-to-develop/java/sub-project-settings/project-version-control.md
Labels: target: ガイド/AP開発手順

#2843 [Dressca] Vite 7 にアップデート
  samples/web-csr/dressca-frontend/admin/package.json
  samples/web-csr/dressca-frontend/consumer/package.json
  samples/web-csr/dressca-frontend/package-lock.json
Labels: target: Dressca

#2840 Vue.js 編のガイドの細かい修正
  documents/contents/guidebooks/how-to-develop/vue-js/create-vuejs-blank-project.md
  documents/contents/guidebooks/how-to-develop/vue-js/css.md
  documents/contents/guidebooks/how-to-develop/vue-js/optional-packages.md
  documents/contents/guidebooks/how-to-develop/vue-js/preparation.md
  documents/contents/guidebooks/how-to-develop/vue-js/setting-workspaces.md
Labels: target: ガイド/AP開発手順

#2844 TypeScriptのコード例の文末セミコロンを削除またはスニペットのリンクに置き換え
  cspell.json
  documents/README.md
  documents/contents/app-architecture/client-side-rendering/frontend-application/index.md
  documents/contents/app-architecture/security/xss.md
  documents/contents/guidebooks/how-to-develop/cors/index.md
  documents/contents/guidebooks/how-to-develop/vue-js/create-api-client-code.md
  documents/contents/guidebooks/how-to-develop/vue-js/error-handler-settings.md
  documents/contents/guidebooks/how-to-develop/vue-js/input-validation.md
  documents/contents/guidebooks/how-to-develop/vue-js/message-management.md
  documents/contents/guidebooks/how-to-develop/vue-js/mock-mode-settings.md
  documents/contents/guidebooks/how-to-develop/vue-js/project-settings.md
  documents/contents/samples/azure-ad-b2c/azure-ad-b2c-consideration.md
  samples/azure-ad-b2c-sample/README.md
Labels: target: アーキテクチャ/CSR, target: ガイド/AP開発手順

#2852 create-vue@3.17.0 から 3.18.0 への変更点を反映
  cspell.json
  documents/contents/guidebooks/how-to-develop/vue-js/create-vuejs-blank-project.md
  samples/azure-ad-b2c-sample/auth-frontend/app/package.json
  samples/azure-ad-b2c-sample/auth-frontend/package-lock.json
  samples/web-csr/dressca-frontend/admin/package.json
  samples/web-csr/dressca-frontend/consumer/package.json
  samples/web-csr/dressca-frontend/package-lock.json
Labels: target: Dressca, target: Azure AD B2C Auth, target: ガイド/AP開発手順

#2754 [DOC]静的コード分析とフォーマット を更新
  documents/contents/guidebooks/how-to-develop/vue-js/static-verification-and-format.md
Labels: target: ガイド/AP開発手順

#2861 使用する create-vue のバージョン情報の誤記を修正
  documents/contents/guidebooks/how-to-develop/vue-js/create-vuejs-blank-project.md
Labels: 不適当, target: ガイド/規約

#2862 リンク先URLの誤りを訂正・略語を新規登録
  documents/contents/guidebooks/how-to-develop/vue-js/static-verification-and-format.md
  documents/includes/abbreviations.md
Labels: 不具合, 内部の改善
