Repository AlesInfiny/maia, pull requests merged in 2025-08, with the labels that each got.

#2906 [AzureADB2CAuth] 使用していない autoprefixer を削除
  samples/azure-ad-b2c-sample/auth-frontend/app/package.json
  samples/azure-ad-b2c-sample/auth-frontend/package-lock.json
Labels: 不具合, target: Azure AD B2C Auth

#2910 サポート環境からWindows 10を削除
  documents/contents/guidebooks/how-to-develop/local-environment/index.md
  documents/contents/images/guidebooks/how-to-develop/java/indicator_display.png
Labels: 不適当, target: ガイド/AP開発手順, target: ガイド/規約

#2912 textlint の検査対象からサンプルの .gradle 配下を除外
  .textlintignore
Labels: 不具合, 内部の改善
